server:
  port: 8020


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-ltjj2zy6.sql.tencentcdb.com:28166/Program1?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Wx123456
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
